version: '2'
services:
  golang:
    container_name: golang-game
    build: .
    command: sh -c "go run *.go --front"
    volumes:
      - ./:/go/src/app
    working_dir: /go/src/app
    ports:
      - "3030:3001"
    environment:
      PORT: 3001
    links:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"